version: '3.8'
services:
  code-editor:
    build: .
    ports:
      - "9000:9000"
    environment:
      - NODE_ENV=production
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 512M
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL