services:
  - type: web
    name: xncode-backend
    plan: starter
    region: oregon
    dockerfilePath: Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: LOG_LEVEL
        value: debug
    healthCheckPath: /health
    privileged: true
    autoDeploy: true
    github:
      repo: https://github.com/pprasoon1/xn-backend
      branch: main
    ports:
      - port: 9000
        protocol: TCP

