
services:
  - type: web
    name: xncode-backend
    plan: starter
    region: oregon
    dockerfilePath: Dockerfile
    dockerBuildArgs:
      - NODE_ENV=production
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /health
    privileged: true  # Required for Docker-in-Docker
    autoDeploy: true
    github:
      repo: https://github.com/pprasoon1/xn-backend
      branch: main
      triggerType: commit
    ports:
      - port: 9000
        protocol: TCP
